#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Trackly — Extension Build Script
# ═══════════════════════════════════════════════════════════════════════════════
# Packages the extension into a ZIP file for Chrome Web Store submission or
# manual side-loading.
#
# Usage:
#   ./build.sh                    # Build with default (dev) config
#   APP_URL=https://app.example.com ./build.sh   # Build with production URL
#   ./build.sh --production       # Same, reads APP_URL from .env
#
# Output:
#   dist/trackly-extension-<timestamp>.zip
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
DIST="$ROOT/dist"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
ZIP_NAME="trackly-extension-$TIMESTAMP.zip"

# ── 1. Resolve APP_URL ────────────────────────────────────────────────────────
if [ -n "${1:-}" ] && [ "$1" = "--production" ]; then
  if [ -f "$ROOT/.env" ]; then
    # shellcheck disable=SC1091
    source "$ROOT/.env"
  fi
fi

if [ -z "${APP_URL:-}" ]; then
  APP_URL="http://localhost:3000"
  echo "[build] No APP_URL set — using default: $APP_URL"
else
  echo "[build] Using APP_URL: $APP_URL"
fi

# ── 2. Clean and create dist ──────────────────────────────────────────────────
rm -rf "$DIST"
mkdir -p "$DIST"

# ── 3. Copy all extension files ───────────────────────────────────────────────
echo "[build] Copying extension files…"

cp "$ROOT/manifest.json"   "$DIST/"
cp "$ROOT/background.js"   "$DIST/"
cp "$ROOT/sidepanel.html"  "$DIST/"
cp "$ROOT/sidepanel.js"    "$DIST/"
cp "$ROOT/sidepanel.css"   "$DIST/"
cp -r "$ROOT/icons"        "$DIST/icons/"

# ── 4. Generate config.js with the resolved APP_URL ───────────────────────────
echo "[build] Generating config.js with APP_URL=$APP_URL"

cat > "$DIST/config.js" <<CONFIGEND
/**
 * Trackly — Extension Configuration
 * Auto-generated by build.sh
 */
const APP_URL = '$APP_URL'
CONFIGEND

# ── 5. Create the ZIP archive ─────────────────────────────────────────────────
echo "[build] Creating ZIP archive…"

# Build in a temp location to avoid including the zip in itself
cd "$DIST"
zip -r -q "/tmp/$ZIP_NAME" .
cd "$ROOT"
mv "/tmp/$ZIP_NAME" "$DIST/$ZIP_NAME"

echo ""
echo "  ✅ Build complete!"
echo "  📦 dist/$ZIP_NAME"
echo ""
echo "  To load in Chrome:"
echo "    1. Go to chrome://extensions"
echo "    2. Enable 'Developer mode' (top-right toggle)"
echo "    3. Click 'Load unpacked' and select: $DIST"
echo "    4. Or drag the ZIP file onto the page to install"
echo ""
