/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PerformanceTokenRouteImport } from './routes/performance.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppMyWorkspacesRouteImport } from './routes/app/my-workspaces'
import { Route as AppMyPerformanceRouteImport } from './routes/app/my-performance'
import { Route as AppDepartmentAnalyticsRouteImport } from './routes/app/department-analytics'
import { Route as AppChangelogRouteImport } from './routes/app/changelog'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppAuditLogsRouteImport } from './routes/app/audit-logs'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppTimeTrackerIndexRouteImport } from './routes/app/time-tracker/index'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/app/workspace/settings'
import { Route as AppWorkspaceMembersRouteImport } from './routes/app/workspace/members'
import { Route as AppWorkspaceCatalogsRouteImport } from './routes/app/workspace/catalogs'
import { Route as AppWorkspaceActivityRouteImport } from './routes/app/workspace/activity'
import { Route as AppTimeTrackerWeekRouteImport } from './routes/app/time-tracker/week'
import { Route as AppTimeTrackerMonthRouteImport } from './routes/app/time-tracker/month'
import { Route as AppTimeTrackerDayRouteImport } from './routes/app/time-tracker/day'
import { Route as ApiImportStreamRouteImport } from './routes/api/import/stream'
import { Route as ApiCronSyncGsheetsRouteImport } from './routes/api/cron/sync-gsheets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppWorkspaceMembersMemberIdRouteImport } from './routes/app/workspace/members.$memberId'
import { Route as AppWorkspaceCatalogsTagsRouteImport } from './routes/app/workspace/catalogs.tags'
import { Route as AppWorkspaceCatalogsRolesRouteImport } from './routes/app/workspace/catalogs.roles'
import { Route as AppWorkspaceCatalogsProjectsRouteImport } from './routes/app/workspace/catalogs.projects'
import { Route as AppWorkspaceCatalogsDepartmentsRouteImport } from './routes/app/workspace/catalogs.departments'
import { Route as AppWorkspaceCatalogsCohortsRouteImport } from './routes/app/workspace/catalogs.cohorts'
import { Route as AppWorkspaceCatalogsClientsRouteImport } from './routes/app/workspace/catalogs.clients'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceTokenRoute = PerformanceTokenRouteImport.update({
  id: '/performance/$token',
  path: '/performance/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWorkspacesRoute = AppMyWorkspacesRouteImport.update({
  id: '/my-workspaces',
  path: '/my-workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPerformanceRoute = AppMyPerformanceRouteImport.update({
  id: '/my-performance',
  path: '/my-performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentAnalyticsRoute = AppDepartmentAnalyticsRouteImport.update({
  id: '/department-analytics',
  path: '/department-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimeTrackerIndexRoute = AppTimeTrackerIndexRouteImport.update({
  id: '/time-tracker/',
  path: '/time-tracker/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
  id: '/workspace/settings',
  path: '/workspace/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceMembersRoute = AppWorkspaceMembersRouteImport.update({
  id: '/workspace/members',
  path: '/workspace/members',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceCatalogsRoute = AppWorkspaceCatalogsRouteImport.update({
  id: '/workspace/catalogs',
  path: '/workspace/catalogs',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceActivityRoute = AppWorkspaceActivityRouteImport.update({
  id: '/workspace/activity',
  path: '/workspace/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerWeekRoute = AppTimeTrackerWeekRouteImport.update({
  id: '/time-tracker/week',
  path: '/time-tracker/week',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerMonthRoute = AppTimeTrackerMonthRouteImport.update({
  id: '/time-tracker/month',
  path: '/time-tracker/month',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerDayRoute = AppTimeTrackerDayRouteImport.update({
  id: '/time-tracker/day',
  path: '/time-tracker/day',
  getParentRoute: () => AppRoute,
} as any)
const ApiImportStreamRoute = ApiImportStreamRouteImport.update({
  id: '/api/import/stream',
  path: '/api/import/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncGsheetsRoute = ApiCronSyncGsheetsRouteImport.update({
  id: '/api/cron/sync-gsheets',
  path: '/api/cron/sync-gsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceMembersMemberIdRoute =
  AppWorkspaceMembersMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AppWorkspaceMembersRoute,
  } as any)
const AppWorkspaceCatalogsTagsRoute =
  AppWorkspaceCatalogsTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AppWorkspaceCatalogsRoute,
  } as any)
const AppWorkspaceCatalogsRolesRoute =
  AppWorkspaceCatalogsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AppWorkspaceCatalogsRoute,
  } as any)
const AppWorkspaceCatalogsProjectsRoute =
  AppWorkspaceCatalogsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AppWorkspaceCatalogsRoute,
  } as any)
const AppWorkspaceCatalogsDepartmentsRoute =
  AppWorkspaceCatalogsDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AppWorkspaceCatalogsRoute,
  } as any)
const AppWorkspaceCatalogsCohortsRoute =
  AppWorkspaceCatalogsCohortsRouteImport.update({
    id: '/cohorts',
    path: '/cohorts',
    getParentRoute: () => AppWorkspaceCatalogsRoute,
  } as any)
const AppWorkspaceCatalogsClientsRoute =
  AppWorkspaceCatalogsClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AppWorkspaceCatalogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/lounge': typeof LoungeRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/department-analytics': typeof AppDepartmentAnalyticsRoute
  '/app/my-performance': typeof AppMyPerformanceRoute
  '/app/my-workspaces': typeof AppMyWorkspacesRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/performance/$token': typeof PerformanceTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-gsheets': typeof ApiCronSyncGsheetsRoute
  '/api/import/stream': typeof ApiImportStreamRoute
  '/app/time-tracker/day': typeof AppTimeTrackerDayRoute
  '/app/time-tracker/month': typeof AppTimeTrackerMonthRoute
  '/app/time-tracker/week': typeof AppTimeTrackerWeekRoute
  '/app/workspace/activity': typeof AppWorkspaceActivityRoute
  '/app/workspace/catalogs': typeof AppWorkspaceCatalogsRouteWithChildren
  '/app/workspace/members': typeof AppWorkspaceMembersRouteWithChildren
  '/app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/app/time-tracker/': typeof AppTimeTrackerIndexRoute
  '/app/workspace/catalogs/clients': typeof AppWorkspaceCatalogsClientsRoute
  '/app/workspace/catalogs/cohorts': typeof AppWorkspaceCatalogsCohortsRoute
  '/app/workspace/catalogs/departments': typeof AppWorkspaceCatalogsDepartmentsRoute
  '/app/workspace/catalogs/projects': typeof AppWorkspaceCatalogsProjectsRoute
  '/app/workspace/catalogs/roles': typeof AppWorkspaceCatalogsRolesRoute
  '/app/workspace/catalogs/tags': typeof AppWorkspaceCatalogsTagsRoute
  '/app/workspace/members/$memberId': typeof AppWorkspaceMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/lounge': typeof LoungeRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/department-analytics': typeof AppDepartmentAnalyticsRoute
  '/app/my-performance': typeof AppMyPerformanceRoute
  '/app/my-workspaces': typeof AppMyWorkspacesRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/performance/$token': typeof PerformanceTokenRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-gsheets': typeof ApiCronSyncGsheetsRoute
  '/api/import/stream': typeof ApiImportStreamRoute
  '/app/time-tracker/day': typeof AppTimeTrackerDayRoute
  '/app/time-tracker/month': typeof AppTimeTrackerMonthRoute
  '/app/time-tracker/week': typeof AppTimeTrackerWeekRoute
  '/app/workspace/activity': typeof AppWorkspaceActivityRoute
  '/app/workspace/catalogs': typeof AppWorkspaceCatalogsRouteWithChildren
  '/app/workspace/members': typeof AppWorkspaceMembersRouteWithChildren
  '/app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/app/time-tracker': typeof AppTimeTrackerIndexRoute
  '/app/workspace/catalogs/clients': typeof AppWorkspaceCatalogsClientsRoute
  '/app/workspace/catalogs/cohorts': typeof AppWorkspaceCatalogsCohortsRoute
  '/app/workspace/catalogs/departments': typeof AppWorkspaceCatalogsDepartmentsRoute
  '/app/workspace/catalogs/projects': typeof AppWorkspaceCatalogsProjectsRoute
  '/app/workspace/catalogs/roles': typeof AppWorkspaceCatalogsRolesRoute
  '/app/workspace/catalogs/tags': typeof AppWorkspaceCatalogsTagsRoute
  '/app/workspace/members/$memberId': typeof AppWorkspaceMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/lounge': typeof LoungeRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/department-analytics': typeof AppDepartmentAnalyticsRoute
  '/app/my-performance': typeof AppMyPerformanceRoute
  '/app/my-workspaces': typeof AppMyWorkspacesRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/performance/$token': typeof PerformanceTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-gsheets': typeof ApiCronSyncGsheetsRoute
  '/api/import/stream': typeof ApiImportStreamRoute
  '/app/time-tracker/day': typeof AppTimeTrackerDayRoute
  '/app/time-tracker/month': typeof AppTimeTrackerMonthRoute
  '/app/time-tracker/week': typeof AppTimeTrackerWeekRoute
  '/app/workspace/activity': typeof AppWorkspaceActivityRoute
  '/app/workspace/catalogs': typeof AppWorkspaceCatalogsRouteWithChildren
  '/app/workspace/members': typeof AppWorkspaceMembersRouteWithChildren
  '/app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/app/time-tracker/': typeof AppTimeTrackerIndexRoute
  '/app/workspace/catalogs/clients': typeof AppWorkspaceCatalogsClientsRoute
  '/app/workspace/catalogs/cohorts': typeof AppWorkspaceCatalogsCohortsRoute
  '/app/workspace/catalogs/departments': typeof AppWorkspaceCatalogsDepartmentsRoute
  '/app/workspace/catalogs/projects': typeof AppWorkspaceCatalogsProjectsRoute
  '/app/workspace/catalogs/roles': typeof AppWorkspaceCatalogsRolesRoute
  '/app/workspace/catalogs/tags': typeof AppWorkspaceCatalogsTagsRoute
  '/app/workspace/members/$memberId': typeof AppWorkspaceMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/lounge'
    | '/onboarding'
    | '/api/health'
    | '/app/analytics'
    | '/app/audit-logs'
    | '/app/calendar'
    | '/app/changelog'
    | '/app/department-analytics'
    | '/app/my-performance'
    | '/app/my-workspaces'
    | '/app/profile'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/performance/$token'
    | '/auth/'
    | '/api/auth/$'
    | '/api/cron/sync-gsheets'
    | '/api/import/stream'
    | '/app/time-tracker/day'
    | '/app/time-tracker/month'
    | '/app/time-tracker/week'
    | '/app/workspace/activity'
    | '/app/workspace/catalogs'
    | '/app/workspace/members'
    | '/app/workspace/settings'
    | '/app/time-tracker/'
    | '/app/workspace/catalogs/clients'
    | '/app/workspace/catalogs/cohorts'
    | '/app/workspace/catalogs/departments'
    | '/app/workspace/catalogs/projects'
    | '/app/workspace/catalogs/roles'
    | '/app/workspace/catalogs/tags'
    | '/app/workspace/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/lounge'
    | '/onboarding'
    | '/api/health'
    | '/app/analytics'
    | '/app/audit-logs'
    | '/app/calendar'
    | '/app/changelog'
    | '/app/department-analytics'
    | '/app/my-performance'
    | '/app/my-workspaces'
    | '/app/profile'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/performance/$token'
    | '/auth'
    | '/api/auth/$'
    | '/api/cron/sync-gsheets'
    | '/api/import/stream'
    | '/app/time-tracker/day'
    | '/app/time-tracker/month'
    | '/app/time-tracker/week'
    | '/app/workspace/activity'
    | '/app/workspace/catalogs'
    | '/app/workspace/members'
    | '/app/workspace/settings'
    | '/app/time-tracker'
    | '/app/workspace/catalogs/clients'
    | '/app/workspace/catalogs/cohorts'
    | '/app/workspace/catalogs/departments'
    | '/app/workspace/catalogs/projects'
    | '/app/workspace/catalogs/roles'
    | '/app/workspace/catalogs/tags'
    | '/app/workspace/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/lounge'
    | '/onboarding'
    | '/api/health'
    | '/app/analytics'
    | '/app/audit-logs'
    | '/app/calendar'
    | '/app/changelog'
    | '/app/department-analytics'
    | '/app/my-performance'
    | '/app/my-workspaces'
    | '/app/profile'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/performance/$token'
    | '/auth/'
    | '/api/auth/$'
    | '/api/cron/sync-gsheets'
    | '/api/import/stream'
    | '/app/time-tracker/day'
    | '/app/time-tracker/month'
    | '/app/time-tracker/week'
    | '/app/workspace/activity'
    | '/app/workspace/catalogs'
    | '/app/workspace/members'
    | '/app/workspace/settings'
    | '/app/time-tracker/'
    | '/app/workspace/catalogs/clients'
    | '/app/workspace/catalogs/cohorts'
    | '/app/workspace/catalogs/departments'
    | '/app/workspace/catalogs/projects'
    | '/app/workspace/catalogs/roles'
    | '/app/workspace/catalogs/tags'
    | '/app/workspace/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoungeRoute: typeof LoungeRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PerformanceTokenRoute: typeof PerformanceTokenRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSyncGsheetsRoute: typeof ApiCronSyncGsheetsRoute
  ApiImportStreamRoute: typeof ApiImportStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/$token': {
      id: '/performance/$token'
      path: '/performance/$token'
      fullPath: '/performance/$token'
      preLoaderRoute: typeof PerformanceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-workspaces': {
      id: '/app/my-workspaces'
      path: '/my-workspaces'
      fullPath: '/app/my-workspaces'
      preLoaderRoute: typeof AppMyWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-performance': {
      id: '/app/my-performance'
      path: '/my-performance'
      fullPath: '/app/my-performance'
      preLoaderRoute: typeof AppMyPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/department-analytics': {
      id: '/app/department-analytics'
      path: '/department-analytics'
      fullPath: '/app/department-analytics'
      preLoaderRoute: typeof AppDepartmentAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changelog': {
      id: '/app/changelog'
      path: '/changelog'
      fullPath: '/app/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-logs': {
      id: '/app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/time-tracker/': {
      id: '/app/time-tracker/'
      path: '/time-tracker'
      fullPath: '/app/time-tracker/'
      preLoaderRoute: typeof AppTimeTrackerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/settings': {
      id: '/app/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/app/workspace/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/members': {
      id: '/app/workspace/members'
      path: '/workspace/members'
      fullPath: '/app/workspace/members'
      preLoaderRoute: typeof AppWorkspaceMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/catalogs': {
      id: '/app/workspace/catalogs'
      path: '/workspace/catalogs'
      fullPath: '/app/workspace/catalogs'
      preLoaderRoute: typeof AppWorkspaceCatalogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/activity': {
      id: '/app/workspace/activity'
      path: '/workspace/activity'
      fullPath: '/app/workspace/activity'
      preLoaderRoute: typeof AppWorkspaceActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/week': {
      id: '/app/time-tracker/week'
      path: '/time-tracker/week'
      fullPath: '/app/time-tracker/week'
      preLoaderRoute: typeof AppTimeTrackerWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/month': {
      id: '/app/time-tracker/month'
      path: '/time-tracker/month'
      fullPath: '/app/time-tracker/month'
      preLoaderRoute: typeof AppTimeTrackerMonthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/day': {
      id: '/app/time-tracker/day'
      path: '/time-tracker/day'
      fullPath: '/app/time-tracker/day'
      preLoaderRoute: typeof AppTimeTrackerDayRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/import/stream': {
      id: '/api/import/stream'
      path: '/api/import/stream'
      fullPath: '/api/import/stream'
      preLoaderRoute: typeof ApiImportStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-gsheets': {
      id: '/api/cron/sync-gsheets'
      path: '/api/cron/sync-gsheets'
      fullPath: '/api/cron/sync-gsheets'
      preLoaderRoute: typeof ApiCronSyncGsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspace/members/$memberId': {
      id: '/app/workspace/members/$memberId'
      path: '/$memberId'
      fullPath: '/app/workspace/members/$memberId'
      preLoaderRoute: typeof AppWorkspaceMembersMemberIdRouteImport
      parentRoute: typeof AppWorkspaceMembersRoute
    }
    '/app/workspace/catalogs/tags': {
      id: '/app/workspace/catalogs/tags'
      path: '/tags'
      fullPath: '/app/workspace/catalogs/tags'
      preLoaderRoute: typeof AppWorkspaceCatalogsTagsRouteImport
      parentRoute: typeof AppWorkspaceCatalogsRoute
    }
    '/app/workspace/catalogs/roles': {
      id: '/app/workspace/catalogs/roles'
      path: '/roles'
      fullPath: '/app/workspace/catalogs/roles'
      preLoaderRoute: typeof AppWorkspaceCatalogsRolesRouteImport
      parentRoute: typeof AppWorkspaceCatalogsRoute
    }
    '/app/workspace/catalogs/projects': {
      id: '/app/workspace/catalogs/projects'
      path: '/projects'
      fullPath: '/app/workspace/catalogs/projects'
      preLoaderRoute: typeof AppWorkspaceCatalogsProjectsRouteImport
      parentRoute: typeof AppWorkspaceCatalogsRoute
    }
    '/app/workspace/catalogs/departments': {
      id: '/app/workspace/catalogs/departments'
      path: '/departments'
      fullPath: '/app/workspace/catalogs/departments'
      preLoaderRoute: typeof AppWorkspaceCatalogsDepartmentsRouteImport
      parentRoute: typeof AppWorkspaceCatalogsRoute
    }
    '/app/workspace/catalogs/cohorts': {
      id: '/app/workspace/catalogs/cohorts'
      path: '/cohorts'
      fullPath: '/app/workspace/catalogs/cohorts'
      preLoaderRoute: typeof AppWorkspaceCatalogsCohortsRouteImport
      parentRoute: typeof AppWorkspaceCatalogsRoute
    }
    '/app/workspace/catalogs/clients': {
      id: '/app/workspace/catalogs/clients'
      path: '/clients'
      fullPath: '/app/workspace/catalogs/clients'
      preLoaderRoute: typeof AppWorkspaceCatalogsClientsRouteImport
      parentRoute: typeof AppWorkspaceCatalogsRoute
    }
  }
}

interface AppWorkspaceCatalogsRouteChildren {
  AppWorkspaceCatalogsClientsRoute: typeof AppWorkspaceCatalogsClientsRoute
  AppWorkspaceCatalogsCohortsRoute: typeof AppWorkspaceCatalogsCohortsRoute
  AppWorkspaceCatalogsDepartmentsRoute: typeof AppWorkspaceCatalogsDepartmentsRoute
  AppWorkspaceCatalogsProjectsRoute: typeof AppWorkspaceCatalogsProjectsRoute
  AppWorkspaceCatalogsRolesRoute: typeof AppWorkspaceCatalogsRolesRoute
  AppWorkspaceCatalogsTagsRoute: typeof AppWorkspaceCatalogsTagsRoute
}

const AppWorkspaceCatalogsRouteChildren: AppWorkspaceCatalogsRouteChildren = {
  AppWorkspaceCatalogsClientsRoute: AppWorkspaceCatalogsClientsRoute,
  AppWorkspaceCatalogsCohortsRoute: AppWorkspaceCatalogsCohortsRoute,
  AppWorkspaceCatalogsDepartmentsRoute: AppWorkspaceCatalogsDepartmentsRoute,
  AppWorkspaceCatalogsProjectsRoute: AppWorkspaceCatalogsProjectsRoute,
  AppWorkspaceCatalogsRolesRoute: AppWorkspaceCatalogsRolesRoute,
  AppWorkspaceCatalogsTagsRoute: AppWorkspaceCatalogsTagsRoute,
}

const AppWorkspaceCatalogsRouteWithChildren =
  AppWorkspaceCatalogsRoute._addFileChildren(AppWorkspaceCatalogsRouteChildren)

interface AppWorkspaceMembersRouteChildren {
  AppWorkspaceMembersMemberIdRoute: typeof AppWorkspaceMembersMemberIdRoute
}

const AppWorkspaceMembersRouteChildren: AppWorkspaceMembersRouteChildren = {
  AppWorkspaceMembersMemberIdRoute: AppWorkspaceMembersMemberIdRoute,
}

const AppWorkspaceMembersRouteWithChildren =
  AppWorkspaceMembersRoute._addFileChildren(AppWorkspaceMembersRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppDepartmentAnalyticsRoute: typeof AppDepartmentAnalyticsRoute
  AppMyPerformanceRoute: typeof AppMyPerformanceRoute
  AppMyWorkspacesRoute: typeof AppMyWorkspacesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTimeTrackerDayRoute: typeof AppTimeTrackerDayRoute
  AppTimeTrackerMonthRoute: typeof AppTimeTrackerMonthRoute
  AppTimeTrackerWeekRoute: typeof AppTimeTrackerWeekRoute
  AppWorkspaceActivityRoute: typeof AppWorkspaceActivityRoute
  AppWorkspaceCatalogsRoute: typeof AppWorkspaceCatalogsRouteWithChildren
  AppWorkspaceMembersRoute: typeof AppWorkspaceMembersRouteWithChildren
  AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRoute
  AppTimeTrackerIndexRoute: typeof AppTimeTrackerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppDepartmentAnalyticsRoute: AppDepartmentAnalyticsRoute,
  AppMyPerformanceRoute: AppMyPerformanceRoute,
  AppMyWorkspacesRoute: AppMyWorkspacesRoute,
  AppProfileRoute: AppProfileRoute,
  AppTimeTrackerDayRoute: AppTimeTrackerDayRoute,
  AppTimeTrackerMonthRoute: AppTimeTrackerMonthRoute,
  AppTimeTrackerWeekRoute: AppTimeTrackerWeekRoute,
  AppWorkspaceActivityRoute: AppWorkspaceActivityRoute,
  AppWorkspaceCatalogsRoute: AppWorkspaceCatalogsRouteWithChildren,
  AppWorkspaceMembersRoute: AppWorkspaceMembersRouteWithChildren,
  AppWorkspaceSettingsRoute: AppWorkspaceSettingsRoute,
  AppTimeTrackerIndexRoute: AppTimeTrackerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoungeRoute: LoungeRoute,
  OnboardingRoute: OnboardingRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  PerformanceTokenRoute: PerformanceTokenRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSyncGsheetsRoute: ApiCronSyncGsheetsRoute,
  ApiImportStreamRoute: ApiImportStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
